name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  SKIP_PREFLIGHT_CHECK: true
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
      env:
        CI: false
        PUBLIC_URL: /happy-birthday/
    - name: Test
      run: yarn test
    #- name: Upload Codecov
    #  run: bash <(curl -s https://codecov.io/bash)
    #  if: ${{ matrix.node-version == '14.x' }}
    - name: Deploy
      if: ${{ github.event_name == 'push' && matrix.node-version == '16.x' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
